var nightBlue = (0, 24, 72)
var purpleSky = '#5F42C0'
var litBuildingTop= '#85F7D3'
var whiteStar = '#fff4ea'
var orangeLights = '#E87A3D'
var offwhite = '#f2f4f6'
var bluesteel = '#5c7287'
var whiteLight = '#F6F7F1'
var darkSteel = '#171c21'
var topRedLight = '#D25282'
var lightYellow = '#ffffe0'
var deepRed = '#FA011F'
var darkBuilding = '#432B39'
var steelBuilding = '#9BAED8'
var purNigthSky = '#0c1445'
var redBrown = '#6B3825'
var techGreen = '#39ff14'
var steels = [offwhite, bluesteel, darkSteel,darkBuilding, steelBuilding,techGreen]
var buildingColors = [steelBuilding, nightBlue, topRedLight]
var lightColors = [litBuildingTop]
var lightgrn = lerpColor(color('white'), color(techGreen), random(45)/50);
var lerpedback = lerpColor(color(purNigthSky), color(bluesteel), random(700)/random(10,800));
var backcolor = lerpColor(lerpedback, color('black'), random(3700)/random(16,4000))
var lightsteel = lerpColor(color(offwhite), color(bluesteel), random(700));
var nightsteel = lerpColor(color(bluesteel), color(darkSteel), random(700));
var aqua = lerpColor(color(bluesteel), color(techGreen), random(700)/random(10,800));
var lightgrn = lerpColor(color('white'), color(techGreen), random(700)/random(10,800));
var allSteels = [lightsteel, nightsteel, aqua, lightgrn]